### ISSUE TITLE
odd messages in dzil build of _other_ packages

### ISSUE THREAD

**Issue by rsrchboy** [SineSwiper/sanity#1]
After adding `TravisYML` to my dzil plugin bundle, on `dzil release` of that package I'm now seeing the following:

```
t/release-consistent-version.t .. Detected current environment to be in "author mode" but couldn't load all
modules. Missing (author) modules were:

  autovivification indirect multidimensional

You should install these modules via CPAN, but these modules are not
required by your users (unless you add them to your META file).
```

Google tells me that this message appears to be from this package :)  How do I use `TravisYML` without seeing these warnings?

**Comment by SineSwiper** [comment]
Hmmm... too many levels of indirection for this message.  It should appear if you're using sanity directly, but not exactly if you're just using a module of mine that is using santiy.

As a workaround, go ahead and install the modules, but I'll keep this bug open and figure out how best to fix it.

**Comment by SineSwiper** [comment]
Ahhhh, strictures is doing this a little smarter than me with a caller check:

https://metacpan.org/source/ETHER/strictures-1.004004/lib/strictures.pm#L40

I'll emulate that behavior.

**Comment by SineSwiper** [comment]
Cut a new version of sanity.  Unfortunately, provide deps will need to be changed on the other modules.  For now, you can just download a new version of sanity.

**Comment by rsrchboy** [comment]
Thanks! :)
