### ISSUE TITLE
Invalid pod causes failure to install

### ISSUE THREAD

**Issue by rwstauner** [SineSwiper/sanity#2]
This line: https://github.com/SineSwiper/sanity/blob/master/weaver.ini#L31

creates pod like this: `L<L<https://github.com/SineSwiper/sanity/issues>|GitHub>`

which causes errors like this:

```
$ podchecker lib/sanity.pm 
*** WARNING: alternative text '' contains non-escaped | or / at line 1169 in file lib/sanity.pm
*** WARNING: nested commands L<...L<...>...> at line 1169 in file lib/sanity.pm
```

and causes the install to fail with:

```
$ make
Skip blib/lib/printuni.pl (unchanged)
Skip blib/lib/README.pod (unchanged)
Skip blib/lib/sanity/BaseCalc.pm (unchanged)
Skip blib/lib/sanity.pm (unchanged)
Manifying blib/man3/README.3
Nested processed encoding. at /home/rando/perl5/perlbrew/perls/5.16.3-st/lib/site_perl/5.16.3/Pod/Simple/BlackBox.pm line 380.
make: *** [manifypods] Error 255
```

I can't even force install it with cpan/cpanm.

**Comment by SineSwiper** [comment]
Yeah, it looks like something I fixed in other weaver.ini files.  For example:

https://github.com/SineSwiper/Dist-Zilla-TravisCI/blob/master/weaver.ini#L31

I should really consider that Pod::Weaver author module, but I think for now, I'm going to just make sure the distros all have the right line in that one.

**Comment by rwstauner** [comment]
While the nested link is a problem for the podchecker, that actually isn't what cause `make` to fail,
strangely it's the position of `=encoding`... putting it first (which is a good practice anyway) fixes the problem.
Moving it to the top of your `weaver.ini` will probably do the trick.

**Comment by SineSwiper** [comment]
Well, given how widespread that other problem was, I sucked it up and created a Pod::Weaver author bundle.  I noticed the encoding thing, too, and move it to the top.

I'll start cutting a release for sanity here soon.  Keeping this issue open until I do.

**Comment by SineSwiper** [comment]
This should be fixed now.
