### ISSUE TITLE
Wishlist: play tricks with %INC

### ISSUE THREAD

**Issue by tobyink** [SineSwiper/sanity#5]
This is just an idea I'm throwing out there. It may be too horrible to contemplate. sanity.pm could do something like this:

```
$INC{"Modern/Perl.pm"} = __FILE__;
sub Modern::Perl::import { @_ = qw(sanity Modern::Perl); goto \&sanity::import; }
```

This would have the effect that if script.pl contained `use Modern::Perl;`, running perl -Msanity script.pl would by-pass the real Modern::Perl module completely (it needn't even be installed).

Or maybe sanity.pm should steer clear of such dirty tricks. How about bundling an insanity.pm that has all those dirty tricks though??

**Comment by SineSwiper** [comment]
Wow, dirty tricks indeed.  Putting files in %INC just looks eeeevil.  Somewhere on the line of (sense.pm.PL)[https://metacpan.org/source/MLEHMANN/common-sense-3.6/sense.pm.PL] from common::sense.  Or worse.  People would call that module hijacking, like worse than monkeypatching.

Really, the biggest problem with the module is the fact that sanity is pushing the dep requirements upstream.  Like if you say:

```
use sanity 'Quote::Code';
```

And release a module like that, you'll have to make sure that your module requires Quote::Code, even though sanity is loading it.  That's something I'd contemplate dirty tricks to solve.  (Not exactly implement, but I would at least think about it.)

Interesting bit of code, though.  Thanks for sharing.
